apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: tempo

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    jsonData:
      tracesToMetrics:
        datasourceUid: prometheus
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "now"
        tags:
          - key: service.name
            value: service_name
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-10m"
        spanEndTimeShift: "10m"
        filterByTraceID: true
        filterBySpanID: false
        customQuery: true
        query: '{traceId="${__trace.traceId}"}'
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
      search:
        hide: false

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      derivedFields:
        - name: traceId
          matcherRegex: 'traceId=([a-f0-9]{32})'
          url: '${__value.raw}'
          datasourceUid: tempo
          urlDisplayLabel: 'Open in Tempo'
        - name: traceId_json
          matcherRegex: '"traceId":"([a-f0-9]{32})"'
          url: '${__value.raw}'
          datasourceUid: tempo
          urlDisplayLabel: 'Open in Tempo'
