-- ============================================================================
-- V4__reconcile_personas.sql — NEUTRALIZED (demo DATA moved to the Python seeder)
--
-- The demo-DATA this migration used to seed (rm_guest, uw_sam, the rm_jane/rm_carlos
-- segment reconcile, and the insurance-underwriting group + membership) now lives in the
-- idempotent Python seeder `scripts/seed-iam-users.py`, run by the conduit-seeder container
-- (scripts/seed-all.sh). The user wants demo data OUT of Flyway migrations; only the
-- STRUCTURAL schema (V1 DDL) stays in Flyway.
--
-- Kept as a no-op (not deleted) so Flyway's applied-migration history stays contiguous.
-- NOTE: because this file's body changed, an EXISTING database that already applied V4 will
-- fail Flyway checksum validation on next start — reseed against a fresh Postgres volume
-- (drop postgres_data) or run `flyway repair`. Fresh installs are unaffected.
-- ============================================================================

-- intentionally empty: see scripts/seed-iam-users.py
