-- ============================================================================
-- V5__abac_segments_map_and_chat_user.sql — NEUTRALIZED (demo DATA moved to Python seeder)
--
-- The demo-DATA this migration used to seed (the `chat_user` role, the per-segment
-- classification MAPs for rm_jane/rm_carlos/uw_sam/rm_guest, the relationship_manager ->
-- chat_user retirement, and the analyst_amy persona) now lives in the idempotent Python
-- seeder `scripts/seed-iam-users.py`, run by the conduit-seeder container. The Python seeder
-- reconciles each principal's roles declaratively, so the relationship_manager -> chat_user
-- retirement is enforced there.
--
-- Kept as a no-op (not deleted) so Flyway history stays contiguous. See the checksum NOTE in
-- V4 for existing databases (reseed on a fresh volume or `flyway repair`).
-- ============================================================================

-- intentionally empty: see scripts/seed-iam-users.py
