-- ============================================================================
-- V7__seed_conduit_admin.sql — NEUTRALIZED (demo DATA moved to Python seeder)
--
-- The demo-DATA this migration used to seed (the `conduit_admin` role and the
-- `insights_admin` user that carries it) now lives in the idempotent Python seeder
-- `scripts/seed-iam-users.py`, run by the conduit-seeder container.
--
-- Kept as a no-op (not deleted) so Flyway history stays contiguous. See the checksum NOTE in
-- V4 for existing databases (reseed on a fresh volume or `flyway repair`).
-- ============================================================================

-- intentionally empty: see scripts/seed-iam-users.py
