-- ============================================================================
-- V8__seed_demo_bankers.sql — NEUTRALIZED (demo DATA moved to Python seeder)
--
-- The demo-DATA this migration used to seed (the eight demo bankers across business lines —
-- rm_nakamura, comm_banker_okoro, wealth_adv_bianchi, ops_analyst_singh, ins_uw_costa,
-- hr_partner_lund, treasury_moreau, multi_rm_fischer — with their per-segment classification
-- maps and chat_user role) now lives in the idempotent Python seeder
-- `scripts/seed-iam-users.py`, run by the conduit-seeder container. The Python seeder also
-- assigns each banker a first-class TEAM (IAM group), which this SQL never did.
--
-- Kept as a no-op (not deleted) so Flyway history stays contiguous. See the checksum NOTE in
-- V4 for existing databases (reseed on a fresh volume or `flyway repair`).
-- ============================================================================

-- intentionally empty: see scripts/seed-iam-users.py
